services:
  event_platform_postgres:
    image: postgres:latest
    container_name: event_platform_postgres
    environment:
      POSTGRES_DB: event_platform
      POSTGRES_USER: event_platform
      POSTGRES_PASSWORD: event_platform
    ports:
      - "54320:5432"

  event_platform_redis:
    image: redis:latest
    container_name: event_platform_redis
    ports:
      - "63790:6379"
